### ISSUE TITLE
经常双击某个单词就崩溃了

### ISSUE THREAD

**Issue by wxh794708907** [804145113/xTransCodelation#4]
如题 还有最好写一下使用方法啊

**Comment by 804145113** [comment]
你好，能描述的详细一点吗，例如Xcode版本，崩溃前代码部分的截图，我才能确定问题。关于使用方法，我已经制作了一个gif演示图片

**Comment by 804145113** [comment]
你这个问题可能就是#5里面系统字体缺失导致的。
